#!/usr/bin/python

import MySQLdb

db = MySQLdb.connect(host = "localhost",
                     user= "root",
                     passwd = "trams",
                     db="trams_test")

cur = db.cursor()

cur.execute("SELECT * FROM User")

for row in cur.fetchall():
    print row


db.close()